apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hello-world-build-task
spec:
  steps:
    - name: build
      image: docker:latest
      script: |
        docker build -t hello-world https://gitlab.com/practical-openshift/hello-world.git 
